# Generated by Django 4.0.3 on 2022-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinpaper',
            name='book',
        ),
        migrations.AddField(
            model_name='bookinpaper',
            name='book',
            field=models.ManyToManyField(to='catalog.book', verbose_name='Książka'),
        ),
    ]
