# Generated by Django 4.0.3 on 2022-03-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_bookinpaper_book_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
        migrations.AddField(
            model_name='bookinpaper',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Ilość egzemplarów papierowych'),
        ),
    ]
