# Generated by Django 4.0.3 on 2022-04-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Nie obowjąnzkowe', null=True, verbose_name='Data smierci'),
        ),
    ]
